name: "Yet Another Slack Notification Github Action"
author: "gladykov"
description: "Send notification to slack"
inputs:
  CHANNEL_ID:
    description: "Channel to send notification to"
    required: true
  TOKEN:
    description: "API Token"
    required: true
  TITLE:
    description: "Title of notification"
    required: true
  STATUS:
    description: "Job status"
    required: true
  MESSAGE:
    description: "Message of notification"
    required: false
  MESSAGE_SUCCESS:
    description: "Message shown when job succeeds"
    required: false
  MESSAGE_FAILURE:
    description: "Message shown when job fails"
    required: false
  BUTTONS:
    description: "JSON with clickable buttons"
    required: false
  ELEMENTS:
    description: "Which elements we should snow in notification. If empty we show all."
    required: false
  MESSAGE_ID:
    description: "If passed, updates existing message"
    required: false
outputs:
  MESSAGE_ID:
    description: "Id of message created / updated"


runs:
  using: node20
  main: "dist/index.js"